version: '.3.3'
services:
  databse:
    image: mysql:5.7
    volumes:
      - db_data-1:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: javalounge_cafe
      MYSQL_USER: javalounge_admin
      MYSQL_PASSWORD: javalounge_master_password
    ports:
      - '3306:3306'
  phpmyadmin:
    depends_on:
      - databse
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: databse
      MYSQL_ROOT_PASSWORD: root
  web:
    depends_on:
      - databse
    image: quay.io/wildfly/wildfly
    volumes:
      - /target/servlet.war:/opt/jboss/wildfly/standalone/deployments/
    ports:
      - '9000:8080'
      - '9990:9990'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: javalounge
      MYSQL_USER: javalounge_admin
      MYSQL_PASSWORD: javalounge_master_password
volumes:
  db_data-1:
    name: db_data-1