version: '.3.3'
services:
  database:
    image: mysql:5.7
    volumes:
      - db_data-1:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: peppermint_cafe
      MYSQL_USER: peppermint_admin
      MYSQL_PASSWORD: peppermint_p
    ports:
      - '5000:3306'
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
  web:
    depends_on:
      - database
    image: tomcat
    volumes:
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./target/servlet.war:/usr/local/tomcat/webapps/servlet.war
    ports:
      - '8082:8080'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: peppermint_cafe
      MYSQL_USER: peppermint_admin
      MYSQL_PASSWORD: peppermint_p
    entrypoint: |
      bash -c 'cp -a webapps.dist/manager webapps/; exec catalina.sh run'
volumes:
  db_data-1:
    name: db_data-1